version: '3.7'

services:
  api:
    image: linkextractor-api:step5-python
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./movie25.csv:/shared_data/movie25.csv


  api2:
    image: instancesecond:step5-python
    build: ./api2
    ports:
      - "5001:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./movie25.csv:/shared_data/movie25.csv

  api3:
    image: instancia3:step5-python
    build: ./api3
    ports:
      - "5002:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./movie25.csv:/shared_data/movie25.csv

  api4:
    image: instancia4:step5-python
    build: ./api4
    ports:
      - "5003:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./movie25.csv:/shared_data/movie25.csv

  api5:
    image: instancia5:step5-python
    build: ./api5
    ports:
      - "5004:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./movie25.csv:/shared_data/movie25.csv

  redis:
    image: redis
